x-exercise: &exercise
  image: oven/bun:1.2-alpine
  entrypoint: /bin/sh

services:
  sync:
    image: "ghcr.io/skiller-whale/learnersync:0.2.1"
    network_mode: "host"
    environment:
      SERVER_URL: "https://train.skillerwhale.com/"
      SW_RUNNING_IN_HOSTED_ENV:
      WATCHER_BASE_PATH: "/exercises"
      ATTENDANCE_ID_FILE: "/attendance_id"
      WATCHED_EXTS: ".js .ts"
      IGNORE_MATCH: ".git node_modules"
    volumes:
      - "./exercises:/exercises:ro"
      - "./attendance_id:/attendance_id:ro"
    tty: true
    stdin_open: true

  introduction_to_tdd:
    <<: *exercise
    volumes:
      - ./exercises/introduction_to_tdd:/introduction_to_tdd
      - introduction_to_tdd_node_modules:/introduction_to_tdd/node_modules
    working_dir: /introduction_to_tdd

  specifying_behaviour:
    <<: *exercise
    volumes:
      - ./exercises/specifying_behaviour:/specifying_behaviour
      - specifying_behaviour_node_modules:/specifying_behaviour/node_modules
    working_dir: /specifying_behaviour

volumes:
  introduction_to_tdd_node_modules:
  specifying_behaviour_node_modules:
