services:
  tests:
    image: oven/bun:1.1-alpine
    volumes:
      - ./exercise_1:/exercises/exercise_1
      - ./package.json:/exercises/package.json
    working_dir: /exercises
    command: ["bun", "test", "--watch"]
    init: true # to ensure signal handling works (and you can kill the container with ctrl-c)
